version: "3"

services:
    postgres:
        image: postgres:12.21
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment: 
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: strongpassword!
        ports:
            - 5432:5432
        networks: 
            - network
            
    keycloak:
        image: keycloak/keycloak:26.0
        command: start-dev
        environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_SCHEMA: public
            KC_DB_PASSWORD: strongpassword!
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin           
        ports:
            - 3333:8080
        depends_on:
            - postgres
        networks:
            - network

    app_one:
        image: nginx:stable-alpine
        networks:
            - network

    app_two:
        image: nginx:stable-alpine
        networks:
            - network

    nginx:
        build:
            context: ./
        ports:
            - 8081:8081
            - 8082:8082            
        networks:
            - network
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
 
networks:
    network:
        name: network
 
volumes:
    postgres_data: